# Generated by Django 4.2.7 on 2024-01-04 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0005_remove_ad_favorites_ad_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favorite_ads",
                through="ads.Fav",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
